# Form implementation generated from reading ui file 'ui/item_list.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from src.data_types import Partner


class Ui_Form(object):
    def setupUi(self, Form, partner: Partner):
        Form.setObjectName("Form")
        Form.resize(400, 108)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, -5, 401, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.type_name = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.type_name.setObjectName("type_name")
        self.verticalLayout_2.addWidget(self.type_name)
        self.director = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.director.setObjectName("director")
        self.verticalLayout_2.addWidget(self.director)
        self.phone = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.phone.setObjectName("phone")
        self.verticalLayout_2.addWidget(self.phone)
        self.rating = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.rating.setObjectName("rating")
        self.verticalLayout_2.addWidget(self.rating)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.skidka = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.skidka.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.skidka.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.skidka.setObjectName("skidka")
        self.horizontalLayout.addWidget(self.skidka)

        self.retranslateUi(Form, partner)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form, partner: Partner):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.type_name.setText(_translate("Form", f"{partner.type }| {partner.name}"))
        self.director.setText(_translate("Form", f"{partner.d_last_name} {partner.d_first_name} {partner.d_sur_name}"))
        self.phone.setText(_translate("Form", f"{partner.phone}"))
        self.rating.setText(_translate("Form", f"Рейтинг: {partner.rating}"))
        self.skidka.setText(_translate("Form", f"{partner.skidka}%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
